# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  ent:
    cmds:
      - go generate ./oracledb
    dir: ./internal/oracle
    sources:
      - oracledb/schema/*.go
    generates:
      - oracledb/*.go
      - oracledb/**/*.go
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test -race -cover ./...
  build:
    deps:
      - ent
    cmds:
      - go build ./cmd/stax
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
