# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  ent:
    cmds:
      - go generate ./oracledb
    dir: ./internal/oracle
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test -race -cover ./...
