# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  ent:
    cmds:
      - go generate ./bones
    dir: ./internal
    sources:
      - bones/schema/*.go
    generates:
      - bones/*.go
      - bones/**/*.go
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test -cover ./...
  build:
    deps:
      - ent
    cmds:
      - go build ./cmd/stax
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
  local-api:
    deps:
      - build
    cmds:
      - ./stax api
