// Code generated by ent, DO NOT EDIT.

package oracledb

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/stax/internal/oracle/oracledb/card"
	"github.com/SethCurry/stax/internal/oracle/oracledb/cardface"
	"github.com/SethCurry/stax/internal/oracle/oracledb/predicate"
	"github.com/SethCurry/stax/internal/oracle/oracledb/ruling"
)

// CardUpdate is the builder for updating Card entities.
type CardUpdate struct {
	config
	hooks    []Hook
	mutation *CardMutation
}

// Where appends a list predicates to the CardUpdate builder.
func (cu *CardUpdate) Where(ps ...predicate.Card) *CardUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "name" field.
func (cu *CardUpdate) SetName(s string) *CardUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *CardUpdate) SetNillableName(s *string) *CardUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetOracleID sets the "oracle_id" field.
func (cu *CardUpdate) SetOracleID(s string) *CardUpdate {
	cu.mutation.SetOracleID(s)
	return cu
}

// SetNillableOracleID sets the "oracle_id" field if the given value is not nil.
func (cu *CardUpdate) SetNillableOracleID(s *string) *CardUpdate {
	if s != nil {
		cu.SetOracleID(*s)
	}
	return cu
}

// SetColorIdentity sets the "color_identity" field.
func (cu *CardUpdate) SetColorIdentity(u uint8) *CardUpdate {
	cu.mutation.ResetColorIdentity()
	cu.mutation.SetColorIdentity(u)
	return cu
}

// SetNillableColorIdentity sets the "color_identity" field if the given value is not nil.
func (cu *CardUpdate) SetNillableColorIdentity(u *uint8) *CardUpdate {
	if u != nil {
		cu.SetColorIdentity(*u)
	}
	return cu
}

// AddColorIdentity adds u to the "color_identity" field.
func (cu *CardUpdate) AddColorIdentity(u int8) *CardUpdate {
	cu.mutation.AddColorIdentity(u)
	return cu
}

// AddFaceIDs adds the "faces" edge to the CardFace entity by IDs.
func (cu *CardUpdate) AddFaceIDs(ids ...int) *CardUpdate {
	cu.mutation.AddFaceIDs(ids...)
	return cu
}

// AddFaces adds the "faces" edges to the CardFace entity.
func (cu *CardUpdate) AddFaces(c ...*CardFace) *CardUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddFaceIDs(ids...)
}

// AddRulingIDs adds the "rulings" edge to the Ruling entity by IDs.
func (cu *CardUpdate) AddRulingIDs(ids ...int) *CardUpdate {
	cu.mutation.AddRulingIDs(ids...)
	return cu
}

// AddRulings adds the "rulings" edges to the Ruling entity.
func (cu *CardUpdate) AddRulings(r ...*Ruling) *CardUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddRulingIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (cu *CardUpdate) Mutation() *CardMutation {
	return cu.mutation
}

// ClearFaces clears all "faces" edges to the CardFace entity.
func (cu *CardUpdate) ClearFaces() *CardUpdate {
	cu.mutation.ClearFaces()
	return cu
}

// RemoveFaceIDs removes the "faces" edge to CardFace entities by IDs.
func (cu *CardUpdate) RemoveFaceIDs(ids ...int) *CardUpdate {
	cu.mutation.RemoveFaceIDs(ids...)
	return cu
}

// RemoveFaces removes "faces" edges to CardFace entities.
func (cu *CardUpdate) RemoveFaces(c ...*CardFace) *CardUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveFaceIDs(ids...)
}

// ClearRulings clears all "rulings" edges to the Ruling entity.
func (cu *CardUpdate) ClearRulings() *CardUpdate {
	cu.mutation.ClearRulings()
	return cu
}

// RemoveRulingIDs removes the "rulings" edge to Ruling entities by IDs.
func (cu *CardUpdate) RemoveRulingIDs(ids ...int) *CardUpdate {
	cu.mutation.RemoveRulingIDs(ids...)
	return cu
}

// RemoveRulings removes "rulings" edges to Ruling entities.
func (cu *CardUpdate) RemoveRulings(r ...*Ruling) *CardUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveRulingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CardUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CardUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CardUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CardUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := card.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`oracledb: validator failed for field "Card.name": %w`, err)}
		}
	}
	if v, ok := cu.mutation.OracleID(); ok {
		if err := card.OracleIDValidator(v); err != nil {
			return &ValidationError{Name: "oracle_id", err: fmt.Errorf(`oracledb: validator failed for field "Card.oracle_id": %w`, err)}
		}
	}
	return nil
}

func (cu *CardUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(card.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.OracleID(); ok {
		_spec.SetField(card.FieldOracleID, field.TypeString, value)
	}
	if value, ok := cu.mutation.ColorIdentity(); ok {
		_spec.SetField(card.FieldColorIdentity, field.TypeUint8, value)
	}
	if value, ok := cu.mutation.AddedColorIdentity(); ok {
		_spec.AddField(card.FieldColorIdentity, field.TypeUint8, value)
	}
	if cu.mutation.FacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.FacesTable,
			Columns: []string{card.FacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedFacesIDs(); len(nodes) > 0 && !cu.mutation.FacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.FacesTable,
			Columns: []string{card.FacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.FacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.FacesTable,
			Columns: []string{card.FacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.RulingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.RulingsTable,
			Columns: []string{card.RulingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruling.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedRulingsIDs(); len(nodes) > 0 && !cu.mutation.RulingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.RulingsTable,
			Columns: []string{card.RulingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruling.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RulingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.RulingsTable,
			Columns: []string{card.RulingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruling.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CardUpdateOne is the builder for updating a single Card entity.
type CardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardMutation
}

// SetName sets the "name" field.
func (cuo *CardUpdateOne) SetName(s string) *CardUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *CardUpdateOne) SetNillableName(s *string) *CardUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetOracleID sets the "oracle_id" field.
func (cuo *CardUpdateOne) SetOracleID(s string) *CardUpdateOne {
	cuo.mutation.SetOracleID(s)
	return cuo
}

// SetNillableOracleID sets the "oracle_id" field if the given value is not nil.
func (cuo *CardUpdateOne) SetNillableOracleID(s *string) *CardUpdateOne {
	if s != nil {
		cuo.SetOracleID(*s)
	}
	return cuo
}

// SetColorIdentity sets the "color_identity" field.
func (cuo *CardUpdateOne) SetColorIdentity(u uint8) *CardUpdateOne {
	cuo.mutation.ResetColorIdentity()
	cuo.mutation.SetColorIdentity(u)
	return cuo
}

// SetNillableColorIdentity sets the "color_identity" field if the given value is not nil.
func (cuo *CardUpdateOne) SetNillableColorIdentity(u *uint8) *CardUpdateOne {
	if u != nil {
		cuo.SetColorIdentity(*u)
	}
	return cuo
}

// AddColorIdentity adds u to the "color_identity" field.
func (cuo *CardUpdateOne) AddColorIdentity(u int8) *CardUpdateOne {
	cuo.mutation.AddColorIdentity(u)
	return cuo
}

// AddFaceIDs adds the "faces" edge to the CardFace entity by IDs.
func (cuo *CardUpdateOne) AddFaceIDs(ids ...int) *CardUpdateOne {
	cuo.mutation.AddFaceIDs(ids...)
	return cuo
}

// AddFaces adds the "faces" edges to the CardFace entity.
func (cuo *CardUpdateOne) AddFaces(c ...*CardFace) *CardUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddFaceIDs(ids...)
}

// AddRulingIDs adds the "rulings" edge to the Ruling entity by IDs.
func (cuo *CardUpdateOne) AddRulingIDs(ids ...int) *CardUpdateOne {
	cuo.mutation.AddRulingIDs(ids...)
	return cuo
}

// AddRulings adds the "rulings" edges to the Ruling entity.
func (cuo *CardUpdateOne) AddRulings(r ...*Ruling) *CardUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddRulingIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (cuo *CardUpdateOne) Mutation() *CardMutation {
	return cuo.mutation
}

// ClearFaces clears all "faces" edges to the CardFace entity.
func (cuo *CardUpdateOne) ClearFaces() *CardUpdateOne {
	cuo.mutation.ClearFaces()
	return cuo
}

// RemoveFaceIDs removes the "faces" edge to CardFace entities by IDs.
func (cuo *CardUpdateOne) RemoveFaceIDs(ids ...int) *CardUpdateOne {
	cuo.mutation.RemoveFaceIDs(ids...)
	return cuo
}

// RemoveFaces removes "faces" edges to CardFace entities.
func (cuo *CardUpdateOne) RemoveFaces(c ...*CardFace) *CardUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveFaceIDs(ids...)
}

// ClearRulings clears all "rulings" edges to the Ruling entity.
func (cuo *CardUpdateOne) ClearRulings() *CardUpdateOne {
	cuo.mutation.ClearRulings()
	return cuo
}

// RemoveRulingIDs removes the "rulings" edge to Ruling entities by IDs.
func (cuo *CardUpdateOne) RemoveRulingIDs(ids ...int) *CardUpdateOne {
	cuo.mutation.RemoveRulingIDs(ids...)
	return cuo
}

// RemoveRulings removes "rulings" edges to Ruling entities.
func (cuo *CardUpdateOne) RemoveRulings(r ...*Ruling) *CardUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveRulingIDs(ids...)
}

// Where appends a list predicates to the CardUpdate builder.
func (cuo *CardUpdateOne) Where(ps ...predicate.Card) *CardUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CardUpdateOne) Select(field string, fields ...string) *CardUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Card entity.
func (cuo *CardUpdateOne) Save(ctx context.Context) (*Card, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CardUpdateOne) SaveX(ctx context.Context) *Card {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CardUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CardUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CardUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := card.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`oracledb: validator failed for field "Card.name": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.OracleID(); ok {
		if err := card.OracleIDValidator(v); err != nil {
			return &ValidationError{Name: "oracle_id", err: fmt.Errorf(`oracledb: validator failed for field "Card.oracle_id": %w`, err)}
		}
	}
	return nil
}

func (cuo *CardUpdateOne) sqlSave(ctx context.Context) (_node *Card, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`oracledb: missing "Card.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, card.FieldID)
		for _, f := range fields {
			if !card.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("oracledb: invalid field %q for query", f)}
			}
			if f != card.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(card.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.OracleID(); ok {
		_spec.SetField(card.FieldOracleID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ColorIdentity(); ok {
		_spec.SetField(card.FieldColorIdentity, field.TypeUint8, value)
	}
	if value, ok := cuo.mutation.AddedColorIdentity(); ok {
		_spec.AddField(card.FieldColorIdentity, field.TypeUint8, value)
	}
	if cuo.mutation.FacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.FacesTable,
			Columns: []string{card.FacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedFacesIDs(); len(nodes) > 0 && !cuo.mutation.FacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.FacesTable,
			Columns: []string{card.FacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.FacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.FacesTable,
			Columns: []string{card.FacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.RulingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.RulingsTable,
			Columns: []string{card.RulingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruling.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedRulingsIDs(); len(nodes) > 0 && !cuo.mutation.RulingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.RulingsTable,
			Columns: []string{card.RulingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruling.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RulingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   card.RulingsTable,
			Columns: []string{card.RulingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruling.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Card{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
