// Code generated by ent, DO NOT EDIT.

package oracledb

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/stax/internal/oracle/oracledb/predicate"
	"github.com/SethCurry/stax/internal/oracle/oracledb/printing"
	"github.com/SethCurry/stax/internal/oracle/oracledb/printingimage"
)

// PrintingImageQuery is the builder for querying PrintingImage entities.
type PrintingImageQuery struct {
	config
	ctx          *QueryContext
	order        []printingimage.OrderOption
	inters       []Interceptor
	predicates   []predicate.PrintingImage
	withPrinting *PrintingQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrintingImageQuery builder.
func (piq *PrintingImageQuery) Where(ps ...predicate.PrintingImage) *PrintingImageQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *PrintingImageQuery) Limit(limit int) *PrintingImageQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *PrintingImageQuery) Offset(offset int) *PrintingImageQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *PrintingImageQuery) Unique(unique bool) *PrintingImageQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *PrintingImageQuery) Order(o ...printingimage.OrderOption) *PrintingImageQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryPrinting chains the current query on the "printing" edge.
func (piq *PrintingImageQuery) QueryPrinting() *PrintingQuery {
	query := (&PrintingClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(printingimage.Table, printingimage.FieldID, selector),
			sqlgraph.To(printing.Table, printing.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, printingimage.PrintingTable, printingimage.PrintingColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PrintingImage entity from the query.
// Returns a *NotFoundError when no PrintingImage was found.
func (piq *PrintingImageQuery) First(ctx context.Context) (*PrintingImage, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{printingimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PrintingImageQuery) FirstX(ctx context.Context) *PrintingImage {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PrintingImage ID from the query.
// Returns a *NotFoundError when no PrintingImage ID was found.
func (piq *PrintingImageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{printingimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *PrintingImageQuery) FirstIDX(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PrintingImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PrintingImage entity is found.
// Returns a *NotFoundError when no PrintingImage entities are found.
func (piq *PrintingImageQuery) Only(ctx context.Context) (*PrintingImage, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{printingimage.Label}
	default:
		return nil, &NotSingularError{printingimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PrintingImageQuery) OnlyX(ctx context.Context) *PrintingImage {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PrintingImage ID in the query.
// Returns a *NotSingularError when more than one PrintingImage ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *PrintingImageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{printingimage.Label}
	default:
		err = &NotSingularError{printingimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PrintingImageQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PrintingImages.
func (piq *PrintingImageQuery) All(ctx context.Context) ([]*PrintingImage, error) {
	ctx = setContextOp(ctx, piq.ctx, "All")
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PrintingImage, *PrintingImageQuery]()
	return withInterceptors[[]*PrintingImage](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *PrintingImageQuery) AllX(ctx context.Context) []*PrintingImage {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PrintingImage IDs.
func (piq *PrintingImageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, "IDs")
	if err = piq.Select(printingimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PrintingImageQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PrintingImageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, "Count")
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*PrintingImageQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PrintingImageQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PrintingImageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, "Exist")
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("oracledb: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PrintingImageQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrintingImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PrintingImageQuery) Clone() *PrintingImageQuery {
	if piq == nil {
		return nil
	}
	return &PrintingImageQuery{
		config:       piq.config,
		ctx:          piq.ctx.Clone(),
		order:        append([]printingimage.OrderOption{}, piq.order...),
		inters:       append([]Interceptor{}, piq.inters...),
		predicates:   append([]predicate.PrintingImage{}, piq.predicates...),
		withPrinting: piq.withPrinting.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithPrinting tells the query-builder to eager-load the nodes that are connected to
// the "printing" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *PrintingImageQuery) WithPrinting(opts ...func(*PrintingQuery)) *PrintingImageQuery {
	query := (&PrintingClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withPrinting = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PrintingImage.Query().
//		GroupBy(printingimage.FieldURL).
//		Aggregate(oracledb.Count()).
//		Scan(ctx, &v)
func (piq *PrintingImageQuery) GroupBy(field string, fields ...string) *PrintingImageGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PrintingImageGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = printingimage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//	}
//
//	client.PrintingImage.Query().
//		Select(printingimage.FieldURL).
//		Scan(ctx, &v)
func (piq *PrintingImageQuery) Select(fields ...string) *PrintingImageSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &PrintingImageSelect{PrintingImageQuery: piq}
	sbuild.label = printingimage.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PrintingImageSelect configured with the given aggregations.
func (piq *PrintingImageQuery) Aggregate(fns ...AggregateFunc) *PrintingImageSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *PrintingImageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("oracledb: uninitialized interceptor (forgotten import oracledb/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !printingimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("oracledb: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PrintingImageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PrintingImage, error) {
	var (
		nodes       = []*PrintingImage{}
		withFKs     = piq.withFKs
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withPrinting != nil,
		}
	)
	if piq.withPrinting != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, printingimage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PrintingImage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PrintingImage{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withPrinting; query != nil {
		if err := piq.loadPrinting(ctx, query, nodes, nil,
			func(n *PrintingImage, e *Printing) { n.Edges.Printing = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *PrintingImageQuery) loadPrinting(ctx context.Context, query *PrintingQuery, nodes []*PrintingImage, init func(*PrintingImage), assign func(*PrintingImage, *Printing)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PrintingImage)
	for i := range nodes {
		if nodes[i].printing_image_printing == nil {
			continue
		}
		fk := *nodes[i].printing_image_printing
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(printing.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "printing_image_printing" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *PrintingImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PrintingImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(printingimage.Table, printingimage.Columns, sqlgraph.NewFieldSpec(printingimage.FieldID, field.TypeInt))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, printingimage.FieldID)
		for i := range fields {
			if fields[i] != printingimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PrintingImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(printingimage.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = printingimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrintingImageGroupBy is the group-by builder for PrintingImage entities.
type PrintingImageGroupBy struct {
	selector
	build *PrintingImageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PrintingImageGroupBy) Aggregate(fns ...AggregateFunc) *PrintingImageGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *PrintingImageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, "GroupBy")
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrintingImageQuery, *PrintingImageGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *PrintingImageGroupBy) sqlScan(ctx context.Context, root *PrintingImageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PrintingImageSelect is the builder for selecting fields of PrintingImage entities.
type PrintingImageSelect struct {
	*PrintingImageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *PrintingImageSelect) Aggregate(fns ...AggregateFunc) *PrintingImageSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *PrintingImageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, "Select")
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrintingImageQuery, *PrintingImageSelect](ctx, pis.PrintingImageQuery, pis, pis.inters, v)
}

func (pis *PrintingImageSelect) sqlScan(ctx context.Context, root *PrintingImageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
