// Code generated by ent, DO NOT EDIT.

package oracledb

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/stax/internal/oracle/oracledb/printing"
	"github.com/SethCurry/stax/internal/oracle/oracledb/printingimage"
)

// PrintingImageCreate is the builder for creating a PrintingImage entity.
type PrintingImageCreate struct {
	config
	mutation *PrintingImageMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (pic *PrintingImageCreate) SetURL(s string) *PrintingImageCreate {
	pic.mutation.SetURL(s)
	return pic
}

// SetImageType sets the "image_type" field.
func (pic *PrintingImageCreate) SetImageType(pt printingimage.ImageType) *PrintingImageCreate {
	pic.mutation.SetImageType(pt)
	return pic
}

// SetPrintingID sets the "printing" edge to the Printing entity by ID.
func (pic *PrintingImageCreate) SetPrintingID(id int) *PrintingImageCreate {
	pic.mutation.SetPrintingID(id)
	return pic
}

// SetNillablePrintingID sets the "printing" edge to the Printing entity by ID if the given value is not nil.
func (pic *PrintingImageCreate) SetNillablePrintingID(id *int) *PrintingImageCreate {
	if id != nil {
		pic = pic.SetPrintingID(*id)
	}
	return pic
}

// SetPrinting sets the "printing" edge to the Printing entity.
func (pic *PrintingImageCreate) SetPrinting(p *Printing) *PrintingImageCreate {
	return pic.SetPrintingID(p.ID)
}

// Mutation returns the PrintingImageMutation object of the builder.
func (pic *PrintingImageCreate) Mutation() *PrintingImageMutation {
	return pic.mutation
}

// Save creates the PrintingImage in the database.
func (pic *PrintingImageCreate) Save(ctx context.Context) (*PrintingImage, error) {
	return withHooks(ctx, pic.sqlSave, pic.mutation, pic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pic *PrintingImageCreate) SaveX(ctx context.Context) *PrintingImage {
	v, err := pic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pic *PrintingImageCreate) Exec(ctx context.Context) error {
	_, err := pic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pic *PrintingImageCreate) ExecX(ctx context.Context) {
	if err := pic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pic *PrintingImageCreate) check() error {
	if _, ok := pic.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`oracledb: missing required field "PrintingImage.url"`)}
	}
	if v, ok := pic.mutation.URL(); ok {
		if err := printingimage.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`oracledb: validator failed for field "PrintingImage.url": %w`, err)}
		}
	}
	if _, ok := pic.mutation.ImageType(); !ok {
		return &ValidationError{Name: "image_type", err: errors.New(`oracledb: missing required field "PrintingImage.image_type"`)}
	}
	if v, ok := pic.mutation.ImageType(); ok {
		if err := printingimage.ImageTypeValidator(v); err != nil {
			return &ValidationError{Name: "image_type", err: fmt.Errorf(`oracledb: validator failed for field "PrintingImage.image_type": %w`, err)}
		}
	}
	return nil
}

func (pic *PrintingImageCreate) sqlSave(ctx context.Context) (*PrintingImage, error) {
	if err := pic.check(); err != nil {
		return nil, err
	}
	_node, _spec := pic.createSpec()
	if err := sqlgraph.CreateNode(ctx, pic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pic.mutation.id = &_node.ID
	pic.mutation.done = true
	return _node, nil
}

func (pic *PrintingImageCreate) createSpec() (*PrintingImage, *sqlgraph.CreateSpec) {
	var (
		_node = &PrintingImage{config: pic.config}
		_spec = sqlgraph.NewCreateSpec(printingimage.Table, sqlgraph.NewFieldSpec(printingimage.FieldID, field.TypeInt))
	)
	if value, ok := pic.mutation.URL(); ok {
		_spec.SetField(printingimage.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := pic.mutation.ImageType(); ok {
		_spec.SetField(printingimage.FieldImageType, field.TypeEnum, value)
		_node.ImageType = value
	}
	if nodes := pic.mutation.PrintingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   printingimage.PrintingTable,
			Columns: []string{printingimage.PrintingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.printing_image_printing = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PrintingImageCreateBulk is the builder for creating many PrintingImage entities in bulk.
type PrintingImageCreateBulk struct {
	config
	err      error
	builders []*PrintingImageCreate
}

// Save creates the PrintingImage entities in the database.
func (picb *PrintingImageCreateBulk) Save(ctx context.Context) ([]*PrintingImage, error) {
	if picb.err != nil {
		return nil, picb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(picb.builders))
	nodes := make([]*PrintingImage, len(picb.builders))
	mutators := make([]Mutator, len(picb.builders))
	for i := range picb.builders {
		func(i int, root context.Context) {
			builder := picb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrintingImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, picb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, picb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, picb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (picb *PrintingImageCreateBulk) SaveX(ctx context.Context) []*PrintingImage {
	v, err := picb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (picb *PrintingImageCreateBulk) Exec(ctx context.Context) error {
	_, err := picb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (picb *PrintingImageCreateBulk) ExecX(ctx context.Context) {
	if err := picb.Exec(ctx); err != nil {
		panic(err)
	}
}
