// Code generated by ent, DO NOT EDIT.

package oracledb

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/stax/internal/oracle/oracledb/predicate"
	"github.com/SethCurry/stax/internal/oracle/oracledb/printingimage"
)

// PrintingImageDelete is the builder for deleting a PrintingImage entity.
type PrintingImageDelete struct {
	config
	hooks    []Hook
	mutation *PrintingImageMutation
}

// Where appends a list predicates to the PrintingImageDelete builder.
func (pid *PrintingImageDelete) Where(ps ...predicate.PrintingImage) *PrintingImageDelete {
	pid.mutation.Where(ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *PrintingImageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pid.sqlExec, pid.mutation, pid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *PrintingImageDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *PrintingImageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(printingimage.Table, sqlgraph.NewFieldSpec(printingimage.FieldID, field.TypeInt))
	if ps := pid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pid.mutation.done = true
	return affected, err
}

// PrintingImageDeleteOne is the builder for deleting a single PrintingImage entity.
type PrintingImageDeleteOne struct {
	pid *PrintingImageDelete
}

// Where appends a list predicates to the PrintingImageDelete builder.
func (pido *PrintingImageDeleteOne) Where(ps ...predicate.PrintingImage) *PrintingImageDeleteOne {
	pido.pid.mutation.Where(ps...)
	return pido
}

// Exec executes the deletion query.
func (pido *PrintingImageDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{printingimage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *PrintingImageDeleteOne) ExecX(ctx context.Context) {
	if err := pido.Exec(ctx); err != nil {
		panic(err)
	}
}
