// Code generated by ent, DO NOT EDIT.

package artist

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the artist type in the database.
	Label = "artist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgePrintings holds the string denoting the printings edge name in mutations.
	EdgePrintings = "printings"
	// Table holds the table name of the artist in the database.
	Table = "artists"
	// PrintingsTable is the table that holds the printings relation/edge.
	PrintingsTable = "printings"
	// PrintingsInverseTable is the table name for the Printing entity.
	// It exists in this package in order to avoid circular dependency with the "printing" package.
	PrintingsInverseTable = "printings"
	// PrintingsColumn is the table column denoting the printings relation/edge.
	PrintingsColumn = "printing_artist"
)

// Columns holds all SQL columns for artist fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Artist queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrintingsCount orders the results by printings count.
func ByPrintingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrintingsStep(), opts...)
	}
}

// ByPrintings orders the results by printings terms.
func ByPrintings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrintingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPrintingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrintingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PrintingsTable, PrintingsColumn),
	)
}
