// Code generated by ent, DO NOT EDIT.

package bones

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/stax/internal/bones/card"
	"github.com/SethCurry/stax/internal/bones/cardface"
	"github.com/SethCurry/stax/internal/bones/predicate"
	"github.com/SethCurry/stax/internal/bones/printing"
)

// CardFaceQuery is the builder for querying CardFace entities.
type CardFaceQuery struct {
	config
	ctx           *QueryContext
	order         []cardface.OrderOption
	inters        []Interceptor
	predicates    []predicate.CardFace
	withCard      *CardQuery
	withPrintings *PrintingQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CardFaceQuery builder.
func (cfq *CardFaceQuery) Where(ps ...predicate.CardFace) *CardFaceQuery {
	cfq.predicates = append(cfq.predicates, ps...)
	return cfq
}

// Limit the number of records to be returned by this query.
func (cfq *CardFaceQuery) Limit(limit int) *CardFaceQuery {
	cfq.ctx.Limit = &limit
	return cfq
}

// Offset to start from.
func (cfq *CardFaceQuery) Offset(offset int) *CardFaceQuery {
	cfq.ctx.Offset = &offset
	return cfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cfq *CardFaceQuery) Unique(unique bool) *CardFaceQuery {
	cfq.ctx.Unique = &unique
	return cfq
}

// Order specifies how the records should be ordered.
func (cfq *CardFaceQuery) Order(o ...cardface.OrderOption) *CardFaceQuery {
	cfq.order = append(cfq.order, o...)
	return cfq
}

// QueryCard chains the current query on the "card" edge.
func (cfq *CardFaceQuery) QueryCard() *CardQuery {
	query := (&CardClient{config: cfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cardface.Table, cardface.FieldID, selector),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, cardface.CardTable, cardface.CardColumn),
		)
		fromU = sqlgraph.SetNeighbors(cfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPrintings chains the current query on the "printings" edge.
func (cfq *CardFaceQuery) QueryPrintings() *PrintingQuery {
	query := (&PrintingClient{config: cfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cardface.Table, cardface.FieldID, selector),
			sqlgraph.To(printing.Table, printing.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, cardface.PrintingsTable, cardface.PrintingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CardFace entity from the query.
// Returns a *NotFoundError when no CardFace was found.
func (cfq *CardFaceQuery) First(ctx context.Context) (*CardFace, error) {
	nodes, err := cfq.Limit(1).All(setContextOp(ctx, cfq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cardface.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cfq *CardFaceQuery) FirstX(ctx context.Context) *CardFace {
	node, err := cfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CardFace ID from the query.
// Returns a *NotFoundError when no CardFace ID was found.
func (cfq *CardFaceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cfq.Limit(1).IDs(setContextOp(ctx, cfq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cardface.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cfq *CardFaceQuery) FirstIDX(ctx context.Context) int {
	id, err := cfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CardFace entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CardFace entity is found.
// Returns a *NotFoundError when no CardFace entities are found.
func (cfq *CardFaceQuery) Only(ctx context.Context) (*CardFace, error) {
	nodes, err := cfq.Limit(2).All(setContextOp(ctx, cfq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cardface.Label}
	default:
		return nil, &NotSingularError{cardface.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cfq *CardFaceQuery) OnlyX(ctx context.Context) *CardFace {
	node, err := cfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CardFace ID in the query.
// Returns a *NotSingularError when more than one CardFace ID is found.
// Returns a *NotFoundError when no entities are found.
func (cfq *CardFaceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cfq.Limit(2).IDs(setContextOp(ctx, cfq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cardface.Label}
	default:
		err = &NotSingularError{cardface.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cfq *CardFaceQuery) OnlyIDX(ctx context.Context) int {
	id, err := cfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CardFaces.
func (cfq *CardFaceQuery) All(ctx context.Context) ([]*CardFace, error) {
	ctx = setContextOp(ctx, cfq.ctx, "All")
	if err := cfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CardFace, *CardFaceQuery]()
	return withInterceptors[[]*CardFace](ctx, cfq, qr, cfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cfq *CardFaceQuery) AllX(ctx context.Context) []*CardFace {
	nodes, err := cfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CardFace IDs.
func (cfq *CardFaceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cfq.ctx.Unique == nil && cfq.path != nil {
		cfq.Unique(true)
	}
	ctx = setContextOp(ctx, cfq.ctx, "IDs")
	if err = cfq.Select(cardface.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cfq *CardFaceQuery) IDsX(ctx context.Context) []int {
	ids, err := cfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cfq *CardFaceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cfq.ctx, "Count")
	if err := cfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cfq, querierCount[*CardFaceQuery](), cfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cfq *CardFaceQuery) CountX(ctx context.Context) int {
	count, err := cfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cfq *CardFaceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cfq.ctx, "Exist")
	switch _, err := cfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("bones: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cfq *CardFaceQuery) ExistX(ctx context.Context) bool {
	exist, err := cfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CardFaceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cfq *CardFaceQuery) Clone() *CardFaceQuery {
	if cfq == nil {
		return nil
	}
	return &CardFaceQuery{
		config:        cfq.config,
		ctx:           cfq.ctx.Clone(),
		order:         append([]cardface.OrderOption{}, cfq.order...),
		inters:        append([]Interceptor{}, cfq.inters...),
		predicates:    append([]predicate.CardFace{}, cfq.predicates...),
		withCard:      cfq.withCard.Clone(),
		withPrintings: cfq.withPrintings.Clone(),
		// clone intermediate query.
		sql:  cfq.sql.Clone(),
		path: cfq.path,
	}
}

// WithCard tells the query-builder to eager-load the nodes that are connected to
// the "card" edge. The optional arguments are used to configure the query builder of the edge.
func (cfq *CardFaceQuery) WithCard(opts ...func(*CardQuery)) *CardFaceQuery {
	query := (&CardClient{config: cfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cfq.withCard = query
	return cfq
}

// WithPrintings tells the query-builder to eager-load the nodes that are connected to
// the "printings" edge. The optional arguments are used to configure the query builder of the edge.
func (cfq *CardFaceQuery) WithPrintings(opts ...func(*PrintingQuery)) *CardFaceQuery {
	query := (&PrintingClient{config: cfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cfq.withPrintings = query
	return cfq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CardFace.Query().
//		GroupBy(cardface.FieldName).
//		Aggregate(bones.Count()).
//		Scan(ctx, &v)
func (cfq *CardFaceQuery) GroupBy(field string, fields ...string) *CardFaceGroupBy {
	cfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CardFaceGroupBy{build: cfq}
	grbuild.flds = &cfq.ctx.Fields
	grbuild.label = cardface.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.CardFace.Query().
//		Select(cardface.FieldName).
//		Scan(ctx, &v)
func (cfq *CardFaceQuery) Select(fields ...string) *CardFaceSelect {
	cfq.ctx.Fields = append(cfq.ctx.Fields, fields...)
	sbuild := &CardFaceSelect{CardFaceQuery: cfq}
	sbuild.label = cardface.Label
	sbuild.flds, sbuild.scan = &cfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CardFaceSelect configured with the given aggregations.
func (cfq *CardFaceQuery) Aggregate(fns ...AggregateFunc) *CardFaceSelect {
	return cfq.Select().Aggregate(fns...)
}

func (cfq *CardFaceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cfq.inters {
		if inter == nil {
			return fmt.Errorf("bones: uninitialized interceptor (forgotten import bones/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cfq); err != nil {
				return err
			}
		}
	}
	for _, f := range cfq.ctx.Fields {
		if !cardface.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("bones: invalid field %q for query", f)}
		}
	}
	if cfq.path != nil {
		prev, err := cfq.path(ctx)
		if err != nil {
			return err
		}
		cfq.sql = prev
	}
	return nil
}

func (cfq *CardFaceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CardFace, error) {
	var (
		nodes       = []*CardFace{}
		withFKs     = cfq.withFKs
		_spec       = cfq.querySpec()
		loadedTypes = [2]bool{
			cfq.withCard != nil,
			cfq.withPrintings != nil,
		}
	)
	if cfq.withCard != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, cardface.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CardFace).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CardFace{config: cfq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cfq.withCard; query != nil {
		if err := cfq.loadCard(ctx, query, nodes, nil,
			func(n *CardFace, e *Card) { n.Edges.Card = e }); err != nil {
			return nil, err
		}
	}
	if query := cfq.withPrintings; query != nil {
		if err := cfq.loadPrintings(ctx, query, nodes,
			func(n *CardFace) { n.Edges.Printings = []*Printing{} },
			func(n *CardFace, e *Printing) { n.Edges.Printings = append(n.Edges.Printings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cfq *CardFaceQuery) loadCard(ctx context.Context, query *CardQuery, nodes []*CardFace, init func(*CardFace), assign func(*CardFace, *Card)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CardFace)
	for i := range nodes {
		if nodes[i].card_face_card == nil {
			continue
		}
		fk := *nodes[i].card_face_card
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(card.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "card_face_card" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cfq *CardFaceQuery) loadPrintings(ctx context.Context, query *PrintingQuery, nodes []*CardFace, init func(*CardFace), assign func(*CardFace, *Printing)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CardFace)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Printing(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(cardface.PrintingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.printing_card_face
		if fk == nil {
			return fmt.Errorf(`foreign-key "printing_card_face" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "printing_card_face" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cfq *CardFaceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cfq.querySpec()
	_spec.Node.Columns = cfq.ctx.Fields
	if len(cfq.ctx.Fields) > 0 {
		_spec.Unique = cfq.ctx.Unique != nil && *cfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cfq.driver, _spec)
}

func (cfq *CardFaceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cardface.Table, cardface.Columns, sqlgraph.NewFieldSpec(cardface.FieldID, field.TypeInt))
	_spec.From = cfq.sql
	if unique := cfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cfq.path != nil {
		_spec.Unique = true
	}
	if fields := cfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cardface.FieldID)
		for i := range fields {
			if fields[i] != cardface.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cfq *CardFaceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cfq.driver.Dialect())
	t1 := builder.Table(cardface.Table)
	columns := cfq.ctx.Fields
	if len(columns) == 0 {
		columns = cardface.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cfq.sql != nil {
		selector = cfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cfq.ctx.Unique != nil && *cfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cfq.predicates {
		p(selector)
	}
	for _, p := range cfq.order {
		p(selector)
	}
	if offset := cfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CardFaceGroupBy is the group-by builder for CardFace entities.
type CardFaceGroupBy struct {
	selector
	build *CardFaceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cfgb *CardFaceGroupBy) Aggregate(fns ...AggregateFunc) *CardFaceGroupBy {
	cfgb.fns = append(cfgb.fns, fns...)
	return cfgb
}

// Scan applies the selector query and scans the result into the given value.
func (cfgb *CardFaceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cfgb.build.ctx, "GroupBy")
	if err := cfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CardFaceQuery, *CardFaceGroupBy](ctx, cfgb.build, cfgb, cfgb.build.inters, v)
}

func (cfgb *CardFaceGroupBy) sqlScan(ctx context.Context, root *CardFaceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cfgb.fns))
	for _, fn := range cfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cfgb.flds)+len(cfgb.fns))
		for _, f := range *cfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CardFaceSelect is the builder for selecting fields of CardFace entities.
type CardFaceSelect struct {
	*CardFaceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cfs *CardFaceSelect) Aggregate(fns ...AggregateFunc) *CardFaceSelect {
	cfs.fns = append(cfs.fns, fns...)
	return cfs
}

// Scan applies the selector query and scans the result into the given value.
func (cfs *CardFaceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cfs.ctx, "Select")
	if err := cfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CardFaceQuery, *CardFaceSelect](ctx, cfs.CardFaceQuery, cfs, cfs.inters, v)
}

func (cfs *CardFaceSelect) sqlScan(ctx context.Context, root *CardFaceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cfs.fns))
	for _, fn := range cfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
