// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/SethCurry/stax/internal/bones"
)

// The ArtistFunc type is an adapter to allow the use of ordinary
// function as Artist mutator.
type ArtistFunc func(context.Context, *bones.ArtistMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f ArtistFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.ArtistMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.ArtistMutation", m)
}

// The CardFunc type is an adapter to allow the use of ordinary
// function as Card mutator.
type CardFunc func(context.Context, *bones.CardMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f CardFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.CardMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.CardMutation", m)
}

// The CardFaceFunc type is an adapter to allow the use of ordinary
// function as CardFace mutator.
type CardFaceFunc func(context.Context, *bones.CardFaceMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f CardFaceFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.CardFaceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.CardFaceMutation", m)
}

// The PrintingFunc type is an adapter to allow the use of ordinary
// function as Printing mutator.
type PrintingFunc func(context.Context, *bones.PrintingMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f PrintingFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.PrintingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.PrintingMutation", m)
}

// The PrintingImageFunc type is an adapter to allow the use of ordinary
// function as PrintingImage mutator.
type PrintingImageFunc func(context.Context, *bones.PrintingImageMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f PrintingImageFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.PrintingImageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.PrintingImageMutation", m)
}

// The RulingFunc type is an adapter to allow the use of ordinary
// function as Ruling mutator.
type RulingFunc func(context.Context, *bones.RulingMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f RulingFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.RulingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.RulingMutation", m)
}

// The SetFunc type is an adapter to allow the use of ordinary
// function as Set mutator.
type SetFunc func(context.Context, *bones.SetMutation) (bones.Value, error)

// Mutate calls f(ctx, m).
func (f SetFunc) Mutate(ctx context.Context, m bones.Mutation) (bones.Value, error) {
	if mv, ok := m.(*bones.SetMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bones.SetMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, bones.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m bones.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m bones.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m bones.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op bones.Op) Condition {
	return func(_ context.Context, m bones.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m bones.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m bones.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m bones.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk bones.Hook, cond Condition) bones.Hook {
	return func(next bones.Mutator) bones.Mutator {
		return bones.MutateFunc(func(ctx context.Context, m bones.Mutation) (bones.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, bones.Delete|bones.Create)
func On(hk bones.Hook, op bones.Op) bones.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, bones.Update|bones.UpdateOne)
func Unless(hk bones.Hook, op bones.Op) bones.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) bones.Hook {
	return func(bones.Mutator) bones.Mutator {
		return bones.MutateFunc(func(context.Context, bones.Mutation) (bones.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []bones.Hook {
//		return []bones.Hook{
//			Reject(bones.Delete|bones.Update),
//		}
//	}
func Reject(op bones.Op) bones.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []bones.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...bones.Hook) Chain {
	return Chain{append([]bones.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() bones.Hook {
	return func(mutator bones.Mutator) bones.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...bones.Hook) Chain {
	newHooks := make([]bones.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
